version: '3'

services:
    nextjs:
        build:
            context: ../../
            dockerfile: ./docker/nextjs/dockerfile
            args:
                ENV: dev
        volumes:
            - "../../${APP_FOLDER}:/var/www/html/"
        ports:
            - "80:3000"
        restart: always
        extra_hosts:
            - "host.docker.internal:host-gateway"