version: '3'

services:
    nextjs:
        build:
            context: ../../
            dockerfile: ./docker/nextjs/dockerfile
            args:
                ENV: testing
                APP_FOLDER: ${APP_FOLDER}
        restart: always
        extra_hosts:
            - "host.docker.internal:host-gateway"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_nextjs.rule=Host(``)"
            - "traefik.http.services.${COMPOSE_PROJECT_NAME}_nextjs.loadbalancer.server.port=3000"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_nextjs.entrypoints=https"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_nextjs.tls=true"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_nextjs.tls.certresolver=myresolver"
networks:
    default:
        name: traefik
        external: true